### PR TITLE
addon flannel add var flannel_iface

### PR DESCRIPTION
**Pull request by carllhw**
addon flannel 

- add var flannel_iface
- fix when expression of `Flannel | Start Resources`

### CODE REVIEW

**Comment by vinkdong** [comment]
```diff
node1 ansible_host=192.168.56.11 ip=192.168.56.11 ansible_user=root ansible_ssh_pass=vagrant ansible_become=true
```
Can ip be empty?

**Comment by carllhw** [comment]
@vinkdong if you insist on using `k8s_interface`, I could change code.

**Comment by vinkdong** [comment]
`ansible_host` and `ip` are always the same,  so the `ip` in inventory/hosts can be empty?

**Comment by carllhw** [comment]
Nope, `ansible_host` just for ssh host, `ip` determine node ip.

**Comment by vinkdong** [comment]
🤝

**Pull request merged**
